import Head from "next/head";
import { FC, useContext } from "react";
import NavBar from "../components/NavBar/NavBar";
import { LangContext } from "../lib/contexts/LangContext";
import styles from "../styles/Home.module.scss";

const Home: FC = () => {
    const { Home: lang } = useContext(LangContext);
    const loginUrl = `https://accounts.spotify.com/authorize?client_id=${process.env.CLIENT_ID}&response_type=code&redirect_uri=${lang.current === "FR" ? process.env.REDIRECT_URI_FR : process.env.REDIRECT_URI}&scope=user-read-recently-played%20user-top-read%20user-read-email%20user-read-private`;

    return (<>        
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <NavBar logged={false} loginUrl={loginUrl}/>
            <main role="main">
                <section className={styles.topSection}>
                    <div className={styles.content}>
                        <h1 className={styles.hero}>{lang.hero[0]}<br/>{lang.hero[1]}<br/>{lang.hero[2]}</h1>
                        <p className={styles.subhero}>{lang.subhero}</p>
                        <a className={styles.buttonIcon} href={loginUrl}>
                            <svg width="19" height="20" viewBox="0 0 19 20">
                                <path d="M1.07272 0.278809L18.012 9.98115L0.992889 19.7292L1.07272 0.278809ZM3.05861 3.72111L3.0071 16.2707L13.988 9.98115L3.05861 3.72111Z"/>
                            </svg>
                            <p>{lang.login} <span className={styles.green}>Spotify</span></p>
                        </a>
                    </div>
                    <img className={styles.longArrow} src="/images/long-arrow.svg" alt=""/>
                    <div className={styles.radialGradient}/>
                    <div className={styles.favoritesContainer}>
                        <img className={styles.disc1} src="/images/disc-1.svg" alt=""/>
                        <img className={styles.disc2} src="/images/disc-2.svg" alt=""/>
                        <img className={styles.disc3} src="/images/disc-3.svg" alt=""/>
                        <img className={styles.artist1} src="/images/the-weeknd.png" alt=""/>
                        <img className={styles.artist2} src="/images/drake.png" alt=""/>
                    </div>
                    <div className={styles.shootingStars}>
                        <img className={styles.shootingStar1} src="/images/shooting-star.svg" alt=""/>
                        <img className={styles.shootingStar2} src="/images/shooting-star.svg" alt=""/>
                        <img className={styles.shootingStar3} src="/images/shooting-star.svg" alt=""/>
                        <img className={styles.shootingStar4} src="/images/shooting-star.svg" alt=""/>
                        <img className={styles.shootingStar5} src="/images/shooting-star.svg" alt=""/>
                    </div>
                </section>
            </main>
    </>)
}

export default Home;
